# Load the data.

In [2]:
import pandas as pd 
import numpy as np

superstore = pd.read_csv("Superstore.csv", encoding='latin1')
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Understand the data.

How many rows and columns.

In [3]:
superstore.shape

(9994, 21)

In [ ]:
What are column name.

In [4]:
superstore.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

What type of data(number, text, date).

In [5]:
superstore.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

# Clean the data.

Check missing values.

In [6]:
superstore.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Remove duplcates

In [7]:
superstore.drop_duplicates().head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
Fix wrong data types (like data column).

In [8]:
superstore.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [9]:
superstore["Order Date"] = pd.to_datetime(superstore['Order Date'], dayfirst=True, errors='coerce')

In [10]:
superstore.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date                   str
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [11]:
superstore["Ship Date"] = pd.to_datetime(superstore["Ship Date"], dayfirst = True, errors = 'coerce')

In [12]:
superstore.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

# Feature Engineering.

Add new columns from existing data.

In [13]:
superstore["Order_Date_Day"] = superstore["Order Date"].dt.day

In [14]:
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0

Monthly Sales Analysis.

In [15]:
superstore["Order_Date_Month"] = superstore["Order Date"].dt.month

In [16]:
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0

Yearly Sales Analysis.

In [17]:
superstore["Order_Date_Year"] = superstore["Order Date"].dt.year

In [18]:
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0

Extract month and year from date.

In [19]:
superstore["Order Date"].dt.month

0        8.0
1        8.0
2       12.0
3       11.0
4       11.0
        ...
9989     NaN
9990     NaN
9991     NaN
9992     NaN
9993     4.0
Name: Order Date, Length: 9994, dtype: float64

In [21]:
superstore["Order Date"].dt.year

0       2016.0
1       2016.0
2       2016.0
3       2015.0
4       2015.0
         ...
9989       NaN
9990       NaN
9991       NaN
9992       NaN
9993    2017.0
Name: Order Date, Length: 9994, dtype: float64

Make a Discount like (No Discount, Low Discount, Medium Discount, High Discount) from using if Condition.

In [72]:
superstore["Discount"]

0       0.00
1       0.00
2       0.00
3       0.45
4       0.20
        ...
9989    0.20
9990    0.00
9991    0.20
9992    0.00
9993    0.00
Name: Discount, Length: 9994, dtype: float64

In [73]:
def discount_category(Discount):
    if Discount == 0:
      print("No Discount")

    elif Discount >= 0.2:
      print("Low Discount")

    elif Discount >= 0.5:
      print("Medium Discount")
    
    else:
      print("High Discount")

In [74]:
superstore["Discount"].apply(discount_category)

No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
High Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
High Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
High Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
High Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
High Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
High Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
High Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
High Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
High Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
High Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
High Discount
Low Discount
No Discount
High Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
High Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
High Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
High Discount
No Discount
High Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
High Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
High Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
High Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
Low Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
Low Discount
No Discount
No Discount
No Discount
Low Discount
No Discount
Low Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
No Discount
Low Discount
Low Discount
Low Discount
No Discount

0       None
1       None
2       None
3       None
4       None
        ...
9989    None
9990    None
9991    None
9992    None
9993    None
Name: Discount, Length: 9994, dtype: object

# Sales Analysis

What is total sales.

In [75]:
superstore["Sales"].sum()

np.float64(2297200.8603)

In [ ]:
which product sells the most?

In [76]:
products = superstore.groupby("Product Name")
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0

In [77]:
products["Sales"].sum().sort_values(ascending = False).head()

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

# Profit Analysis

In [ ]:
What is Total Profit.

In [78]:
superstore["Profit"].sum()

np.float64(286397.0217)

Make High Profits Value from filtering.

In [22]:
High_Profits = superstore[superstore["Profit"] > 200]

In [23]:
High_Profits.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,11.0,8.0,2016.0
24,25,CA-2015-106320,NaT,NaT,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.63,3,0.0,240.2649,NaN,NaN,NaN
54,55,CA-2016-105816,2016-11-12,NaT,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.95,5,0.0,298.6855,12.0,11.0,2016.0
144,145,CA-2017-155376,NaT,NaT,Standard Class,SG-20080,Sandra Glassco,Consumer,United States,Independence,...,Office Supplies,Appliances,Sanyo 2.5 Cubic Foot Mid-Size Office Refrigera...,839.43,3,0.0,218.2518,NaN,NaN,NaN
149,150,CA-2016-114489,2016-05-12,2016-09-12,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.84,8,0.0,585.5520,12.0,5.0,2016.0

Make Low Profits value from filtering.

In [24]:
Low_Profits = superstore[superstore["Profit"] < -50]

In [25]:
Low_Profits.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
14,15,US-2015-118983,NaT,NaT,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,NaN,NaN,NaN
27,28,US-2015-150630,NaT,NaT,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,NaN,NaN,NaN
36,37,CA-2016-117590,2016-08-12,2016-10-12,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630,12.0,8.0,2016.0
72,73,US-2015-134026,NaT,2015-02-05,Standard Class,JE-15745,Joel Eaton,Consumer,United States,Memphis,...,Furniture,Chairs,High-Back Leather Manager's Chair,831.9360,8,0.20,-114.3912,NaN,NaN,NaN

# Category Performance Analysis.

Compare both categories which better.

In [79]:
categories["Sales"].sum().sort_values(ascending = False)

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [80]:
categories["Profit"].sum().sort_values(ascending = False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

Which Category Performs Best.

In [81]:
categories = superstore.groupby("Category")
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0

# Regional Analysis.

Which region has highest sales.

In [85]:
Region = superstore.groupby("Region")
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0

Compare Sales Across The Region.

In [82]:
Region["Sales"].max()

Region
Central    17499.950
East       11199.968
South      22638.480
West       13999.960
Name: Sales, dtype: float64

In [ ]:
Compare Profit Across The Region.

In [84]:
Region["Profit"].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# Monthly Trend Analysis.

How Sales Change Month By Month.

In [42]:
Months = superstore.groupby("Order_Date_Month")
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0

In [43]:
Months["Sales"].sum()

Order_Date_Month
1.0      95524.5664
2.0     105139.1240
3.0      72319.9246
4.0      68162.3390
5.0      64520.5088
6.0      53306.8580
7.0      62610.9065
8.0     101577.9506
9.0      66582.3650
10.0     62993.8410
11.0     69615.2315
12.0     65563.6962
Name: Sales, dtype: float64

# Final Business Insight

Technology category generates highest sales and profit.
Some products generate losses despite high sales.
High discounts often reduce profitability.
Sales increase significantly in certain months.
Business performance changes across categories and regions.

Some products are in loss.

In [48]:
superstore[superstore["Profit"] < 0].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
14,15,US-2015-118983,NaT,NaT,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,NaN,NaN,NaN
15,16,US-2015-118983,NaT,NaT,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160,NaN,NaN,NaN
23,24,US-2017-156909,NaT,NaT,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196,NaN,NaN,NaN
27,28,US-2015-150630,NaT,NaT,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,NaN,NaN,NaN

In [55]:
product = superstore.groupby("Product Name")
product.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9974,9975,US-2016-103674,2016-06-12,2016-10-12,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,Office Supplies,Art,Blackstonian Pencils,18.6900,7,0.00,5.2332,12.0,6.0,2016.0
9977,9978,US-2016-103674,2016-06-12,2016-10-12,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.8600,7,0.00,0.0000,12.0,6.0,2016.0
9979,9980,US-2016-103674,2016-06-12,2016-10-12,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152,12.0,6.0,2016.0
9987,9988,CA-2017-163629,NaT,NaT,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964,NaN,NaN,NaN
9988,9989,CA-2017-163629,NaT,NaT,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470,NaN,NaN,NaN

In [60]:
product["Profit"].sum().sort_values()

Product Name
Cubify CubeX 3D Printer Double Head Print                                      -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                                      -4589.9730
Cubify CubeX 3D Printer Triple Head Print                                      -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases                       -2876.1156
Bush Advantage Collection Racetrack Conference Table                           -1934.3976
                                                                                  ...
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Canon PC1060 Personal Laser Copier                                              4570.9347
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Name: Profit, Length: 1850, dtype: float64

Sales increase in certain months.

In [63]:
Months = superstore.groupby("Order_Date_Month")
Months.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Date_Day,Order_Date_Month,Order_Date_Year
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11.0,8.0,2016.0
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11.0,8.0,2016.0
2,3,CA-2016-138688,2016-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6.0,12.0,2016.0
3,4,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10.0,11.0,2015.0
4,5,US-2015-108966,2015-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10.0,11.0,2015.0
5,6,CA-2014-115812,2014-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,6.0,9.0,2014.0
6,7,CA-2014-115812,2014-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656,6.0,9.0,2014.0
7,8,CA-2014-115812,2014-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,6.0,9.0,2014.0
8,9,CA-2014-115812,2014-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825,6.0,9.0,2014.0
9,10,CA-2014-115812,2014-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700,6.0,9.0,2014.0
13,14,CA-2016-161389,2016-05-12,2016-10-12,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922,12.0,5.0,2016.0
16,17,CA-2014-105893,2014-11-11,NaT,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,6,0.00,13.3176,11.0,11.0,2014.0
35,36,CA-2016-117590,2016-08-12,2016-10-12,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737,12.0,8.0,2016.0
36,37,CA-2016-117590,2016-08-12,2016-10-12,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630,12.0,8.0,2016.0
41,42,CA-2017-120999,2017-10-09,NaT,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,...,Technology,Phones,Panasonic Kx-TS550,147.1680,4,0.20,16.5564,9.0,10.0,2017.0
44,45,CA-2016-118255,2016-11-03,NaT,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,...,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.9800,2,0.00,19.7714,3.0,11.0,2016.0
45,46,CA-2016-118255,2016-11-03,NaT,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,...,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.4600,2,0.00,8.2062,3.0,11.0,2016.0
67,68,CA-2014-106376,2014-05-12,2014-10-12,Standard Class,BS-11590,Brendan Sweed,Corporate,United States,Gilbert,...,Office Supplies,Art,Hunt BOSTON Model 1606 High-Volume Electric Pe...,1113.0240,8,0.20,111.3024,12.0,5.0,2014.0
68,69,CA-2014-106376,2014-05-12,2014-10-12,Standard Class,BS-11590,Brendan Sweed,Corporate,United States,Gilbert,...,Technology,Phones,netTALK DUO VoIP Telephone Service,167.9680,4,0.20,62.9880,12.0,5.0,2014.0
69,70,CA-2016-119823,2016-04-06,2016-06-06,First Class,KD-16270,Karen Daniels,Consumer,United States,Springfield,...,Office Supplies,Paper,Snap-A-Way Black Print Carbonless Ruled Speed ...,75.8800,2,0.00,35.6636,6.0,4.0,2016.0
79,80,CA-2016-127208,2016-12-06,NaT,First Class,SC-20770,Stewart Carmichael,Corporate,United States,Decatur,...,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",208.1600,1,0.00,56.2032,6.0,12.0,2016.0
80,81,CA-2016-127208,2016-12-06,NaT,First Class,SC-20770,Stewart Carmichael,Corporate,United States,Decatur,...,Office Supplies,Binders,Avery Heavy-Duty EZD Binder With Locking Rings,16.7400,3,0.00,8.0352,6.0,12.0,2016.0
81,82,CA-2014-139451,2014-12-10,NaT,Standard Class,DN-13690,Duane Noonan,Consumer,United States,San Francisco,...,Office Supplies,Art,"Premium Writing Pencils, Soft, #2 by Central A...",14.9000,5,0.00,4.1720,10.0,12.0,2014.0
82,83,CA-2014-139451,2014-12-10,NaT,Standard Class,DN-13690,Duane Noonan,Consumer,United States,San Francisco,...,Office Supplies,Storage,Sortfiler Multipurpose Personal File Organizer...,21.3900,1,0.00,6.2031,10.0,12.0,2014.0
83,84,CA-2015-149734,2015-03-09,2015-08-09,Standard Class,JC-16105,Julie Creighton,Corporate,United States,Durham,...,Office Supplies,Envelopes,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,200.9840,7,0.20,62.8075,9.0,3.0,2015.0
88,89,CA-2016-159695,2016-05-04,2016-10-04,Second Class,GM-14455,Gary Mitchum,Home Office,United States,Houston,...,Office Supplies,Storage,Eldon Portable Mobile Manager,158.3680,7,0.20,13.8572,4.0,5.0,2016.0
95,96,US-2017-109484,2017-06-11,2017-12-11,Standard Class,RB-19705,Roger Barcio,Home Office,United States,Portland,...,Office Supplies,Binders,Flexible Leather- Look Classic Collection Ring...,5.6820,1,0.70,-3.7880,11.0,6.0,2017.0
98,99,CA-2016-149223,2016-06-09,2016-11-09,Standard Class,ER-13855,Elpida Rittenbach,Corporate,United States,Saint Paul,...,Office Supplies,Appliances,Fellowes Basic Home/Office Series Surge Protec...,77.8800,6,0.00,22.5852,9.0,6.0,2016.0
102,103,CA-2016-129903,2016-01-12,2016-04-12,Second Class,GZ-14470,Gary Zandusky,Consumer,United States,Rochester,...,Office Supplies,Paper,Universal Premium White Copier/Laser Paper (20...,23.9200,4,0.00,11.7208,12.0,1.0,2016.0
111,112,CA-2016-128867,2016-03-11,2016-10-11,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Urbandale,...,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",75.9600,2,0.00,22.7880,11.0,3.0,2016.0
112,113,CA-2016-128867,2016-03-11,2016-10-11,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Urbandale,...,Office Supplies,Binders,"Avery Durable Plastic 1"" Binders",27.2400,6,0.00,13.3476,11.0,3.0,2016.0
117,118,CA-2015-110457,2015-02-03,2015-06-03,Standard Class,DK-13090,Dave Kipp,Consumer,United States,Seattle,...,Furniture,Tables,Hon Racetrack Conference Tables,787.5300,3,0.00,165.3813,3.0,2.0,2015.0
118,119,US-2015-136476,2015-05-04,2015-10-04,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,Bristol,...,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.7940,1,0.70,-115.7156,4.0,5.0,2015.0
128,129,US-2016-125969,2016-06-11,2016-10-11,Second Class,LS-16975,Lindsay Shagiari,Home Office,United States,Los Angeles,...,Furniture,Chairs,"Global Task Chair, Black",81.4240,2,0.20,-9.1602,11.0,6.0,2016.0
129,130,US-2016-125969,2016-06-11,2016-10-11,Second Class,LS-16975,Lindsay Shagiari,Home Office,United States,Los Angeles,...,Furniture,Furnishings,Eldon Cleatmat Plus Chair Mats for High Pile C...,238.5600,3,0.00,26.2416,11.0,6.0,2016.0
130,131,US-2017-164147,2017-02-02,2017-05-02,First Class,DW-13585,Dorothy Wardle,Corporate,United States,Columbus,...,Technology,Phones,Anker 36W 4-Port USB Wall Charger Travel Power...,59.9700,5,0.40,-11.9940,2.0,2.0,2017.0
131,132,US-2017-164147,2017-02-02,2017-05-02,First Class,DW-13585,Dorothy Wardle,Corporate,United States,Columbus,...,Office Supplies,Paper,Xerox 1916,78.3040,2,0.20,29.3640,2.0,2.0,2017.0
132,133,US-2017-164147,2017-02-02,2017-05-02,First Class,DW-13585,Dorothy Wardle,Corporate,United States,Columbus,...,Office Supplies,Fasteners,Staples,21.4560,9,0.20,6.9732,2.0,2.0,2017.0
145,146,CA-2015-110744,2015-07-09,2015-12-09,Standard Class,HA-14920,Helen Andreada,Consumer,United States,Pasadena,...,Office Supplies,Storage,Safco Industrial Wire Shelving,671.9300,7,0.00,20.1579,9.0,7.0,2015.0
157,158,CA-2014-104269,2014-01-03,2014-06-03,Second Class,DB-13060,Dave Brooks,Consumer,United States,Seattle,...,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.5680,2,0.20,51.4764,3.0,1.0,2014.0
163,164,CA-2016-113817,2016-07-11,2016-11-11,Standard Class,MJ-17740,Max Jones,Consumer,United States,Seattle,...,Office Supplies,Binders,Wilson Jones International Size A4 Ring Binders,27.6800,2,0.20,9.6880,11.0,7.0,2016.0
164,165,CA-2014-139892,2014-08-09,2014-12-09,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,Office Supplies,Art,BIC Brite Liner Highlighters,9.9360,3,0.20,2.7324,9.0,8.0,2014.0
197,198,CA-2017-107720,2017-06-11,NaT,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Westfield,...,Office Supplies,Storage,Decoflex Hanging Personal Folder File,46.2600,3,0.00,12.0276,11.0,6.0,2017.0
201,202,CA-2014-133690,2014-03-08,2014-05-08,First Class,BS-11755,Bruce Stewart,Consumer,United States,Denver,...,Furniture,Tables,BoxOffice By Design Rectangular and Half-Moon ...,218.7500,2,0.50,-161.8750,8.0,3.0,2014.0
202,203,CA-2014-133690,2014-03-08,2014-05-08,First Class,BS-11755,Bruce Stewart,Consumer,United States,Denver,...,Office Supplies,Appliances,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",2.6000,1,0.20,0.2925,8.0,3.0,2014.0
206,207,CA-2017-135860,2017-01-12,2017-07-12,Standard Class,JH-15985,Joseph Holt,Consumer,United States,Saginaw,...,Office Supplies,Storage,"Tennsco Lockers, Gray",83.9200,4,0.00,5.8744,12.0,1.0,2017.0
207,208,CA-2017-135860,2017-01-12,2017-07-12,Standard Class,JH-15985,Joseph Holt,Consumer,United States,Saginaw,...,Technology,Phones,Panasonic KX-TG6844B Expandable Digital Cordle...,131.9800,2,0.00,35.6346,12.0,1.0,2017.0
208,209,CA-2017-135860,2017-01-12,2017-07-12,Standard Class,JH-15985,Joseph Holt,Consumer,United States,Saginaw,...,Office Supplies,Binders,"Avery Durable Slant Ring Binders, No Labels",15.9200,4,0.00,7.4824,12.0,1.0,2017.0
212,213,CA-2015-146262,2015-02-01,2015-09-01,Standard Class,VW-21775,Victoria Wilson,Corporate,United States,Medina,...,Office Supplies,Labels,Avery 505,23.6800,2,0.20,8.8800,1.0,2.0,2015.0
231,232,US-2017-100930,2017-07-04,2017-12-04,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,Furniture,Tables,Bush Advantage Collection Round Conference Table,233.8600,2,0.45,-102.0480,4.0,7.0,2017.0
232,233,US-2017-100930,2017-07-04,2017-12-04,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,Furniture,Tables,Bretford Rectangular Conference Table Tops,620.6145,3,0.45,-248.2458,4.0,7.0,2017.0
233,234,US-2017-100930,2017-07-04,2017-12-04,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,Office Supplies,Binders,GBC Instant Index System for Binding Systems,5.3280,2,0.70,-3.5520,4.0,7.0,2017.0
237,238,CA-2016-157749,2016-04-06,2016-09-06,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,Office Supplies,Paper,Xerox 1957,25.9200,5,0.20,9.3960,6.0,4.0,2016.0
238,239,CA-2016-157749,2016-04-06,2016-09-06,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,Furniture,Furnishings,Luxo Professional Fluorescent Magnifier Lamp w...,419.6800,5,0.60,-356.7280,6.0,4.0,2016.0
239,240,CA-2016-157749,2016-04-06,2016-09-06,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,Furniture,Furnishings,Staple-based wall hangings,11.6880,3,0.60,-4.6752,6.0,4.0,2016.0
240,241,CA-2016-157749,2016-04-06,2016-09-06,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,Technology,Phones,PureGear Roll-On Screen Protector,31.9840,2,0.20,11.1944,6.0,4.0,2016.0
249,250,CA-2016-154739,2016-10-12,NaT,Second Class,LH-17155,Logan Haushalter,Consumer,United States,San Francisco,...,Furniture,Chairs,Global Leather Highback Executive Chair with P...,321.5680,2,0.20,28.1372,12.0,10.0,2016.0
252,253,CA-2016-146941,2016-10-12,NaT,First Class,DL-13315,Delfina Latchford,Consumer,United States,New York City,...,Office Supplies,Storage,"Fellowes Personal Hanging Folder Files, Navy",80.5800,6,0.00,22.5624,12.0,10.0,2016.0
253,254,CA-2016-146941,2016-10-12,NaT,First Class,DL-13315,Delfina Latchford,Consumer,United States,New York City,...,Office Supplies,Envelopes,Tyvek Side-Opening Peel & Seel Expanding Envel...,361.9200,4,0.00,162.8640,12.0,10.0,2016.0
265,266,CA-2015-155040,2015-10-11,NaT,Standard Class,AH-10210,Alan Hwang,Consumer,United States,Brentwood,...,Technology,Accessories,Microsoft Sculpt Comfort Mouse,79.9000,2,0.00,35.1560,11.0,10.0,2015.0

In [71]:
Months["Sales"].sum().sort_values(ascending = False)

Order_Date_Month
2.0     105139.1240
8.0     101577.9506
1.0      95524.5664
3.0      72319.9246
11.0     69615.2315
4.0      68162.3390
9.0      66582.3650
12.0     65563.6962
5.0      64520.5088
10.0     62993.8410
7.0      62610.9065
6.0      53306.8580
Name: Sales, dtype: float64

# Sales performance varies by month, with February generating the highest sales, indicating seasonal demand trends.